### ISSUE TITLE
fix typo: castles_maXi.svg

### ISSUE THREAD

**Issue by ghost** [watchout-tw/dev.wevote.tw#7]

**Comment by chihhhhhao** [comment]
直接進入 /issues/ 會出現以下訊息：

```
{"error":"Error: Cannot find module './images/castles_maxi.svg'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:289:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at MaXiCastle.render (/app/src/components/MaXiCastle/MaXiCastle.js:8:16)
at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/app/node_modules/react/lib/ReactCompositeComponent.js:789:34)
at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/app/node_modules/react/lib/ReactCompositeComponent.js:816:14)
at [object Object].ReactCompositeComponentMixin.mountComponent (/app/node_modules/react/lib/ReactCompositeComponent.js:237:30)
at Object.ReactReconciler.mountComponent (/app/node_modules/react/lib/ReactReconciler.js:38:35)
at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/app/node_modules/react/lib/ReactMultiChild.js:192:44)"}
```

**Comment by ghost** [comment]
fixed
